# Generated by Django 2.0 on 2019-11-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecEssayDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_title', models.CharField(max_length=255, verbose_name='标题')),
                ('index_time', models.DateTimeField(verbose_name='时间')),
                ('index_type', models.IntegerField(max_length=20, verbose_name='分类')),
                ('index_url', models.CharField(max_length=255, verbose_name='链接')),
            ],
        ),
    ]
