# Generated by Django 2.0 on 2019-11-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secessaydict',
            name='index_type',
            field=models.IntegerField(verbose_name='分类'),
        ),
    ]
