# Generated by Django 2.0 on 2019-11-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0004_secessaydict_index_sharer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secessaydict',
            name='index_sharer',
            field=models.CharField(blank=True, editable=False, max_length=25, verbose_name='分享者'),
        ),
    ]
